// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzkjycoryfkyhnljohes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6a2p5Y29yeWZreWhubGpvaGVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMzgzNTcsImV4cCI6MjA2MzcxNDM1N30.SMNCVqW-3_BQp3XumoculpT-4i-YQJUnCSA5vm_hsis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);